Update README.md
K3orecki/trafalgar-landing-page pull request #2
Opened 2022-05-15 23:14 UTC by K3orecki

2022-05-27 15:05 UTC, purbanski-deftcode commented
Przy 830px strona ma nienaturalnie przesunięte elementy w lewo:
![Template-Trafalgar 2022-05-27 17-04-46](https://user-images.githubusercontent.com/16034577/170726719-4dedbcbe-4c31-4150-866a-bced926563f0.jpg)

2022-05-27 15:07 UTC, purbanski-deftcode requested changes

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/css/style.css.map
> -{"version":3,"sources":["../scss/_variables.scss","style.css","../scss/_base-styles.scss","../scss/_sections.scss","../scss/_grid.scss","../scss/_navigation-general.scss","../scss/_navbar-animation.s
Ten cały plik nigdy nie powinien znaleźć się na repo. To jest plik, który jest automatycznie generowany na podstawie innego pliku a takie pliki generowane na podstawie innych plików rzadko kiedy lądują na repo. Dodatkowo to jest głównie przydatne programistom do debugowania kodu i ma mniejsze znaczenie np. po deployu na prodzie.

2022-05-27 15:07 UTC, purbanski-deftcode commented on index.html
> +            <nav id="navbar-navigation" class="navbar-navigation mobile-padding active">
A ja się dziwiłem czemu mam menu otwarte na mobilce -> chyba masz robotę do dokończenia w tym pliku.

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
> +function getCarouselButtons() {
Wygląda na to, że ta funkcja jest nieużywana

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
> +function getCarouselItems() {
Wygląda na to, że ta funkcja jest nieużywana

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
> +function getParsedCurrentTargetValue(e) {
Wygląda na to, że ta funkcja jest nieużywana

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
> +function getAbsoluteDifferenceValue(firstValue, secondValue) {
Wygląda na to, że ta funkcja jest nieużywana

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
> +const timerId1 = [];
Bro?

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
>  function getParsedElementId(elementId) {
To co robisz w tym pliku nazywam powszechnie over-engineering. Złożoność tego kodu przez zabiegi takie jak parsowanie ID żeby go spasować z nazwą zmiennej trochę przewyższa zyski jakie z tego niesiesz przy tak małej stronie. Dodatkowo pobieranie przycisków od karuzeli powinno się odbywać inaczej -> wszystkie znajdują się w kontenerze `pagination-dots` co powinieneś wykorzystać.

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
> +    // old working version
remove pls

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
> +    let timerId = setTimeout(function callback() {
czemu `let`?

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
> +    let timerId = setTimeout(function callback() {
co do zasady do `setTimeout` wrzucamy po prostu anonimową funkcję strzałkową

2022-05-27 15:07 UTC, purbanski-deftcode commented on assets/js/main.js
> +const PAGINATION_DOT_BTN_ACTIVE_CLASS = "pagination-dot-btn--active";
double quotes

2022-05-27 15:51 UTC, K3orecki commented on assets/js/main.js
> +const timerId1 = [];
xDDDD

2022-06-01 11:04 UTC, purbanski-deftcode approved these changes
@K3orecki daję approve bo ostatnie zmiany są małe -> po tym możesz mergować.

2022-06-01 11:04 UTC, purbanski-deftcode commented on assets/css/style.css
> +@charset "UTF-8";
Jeśli używasz SCSS to de facto cały wynikowy CSS w repozytorium jest zbędny. Nie tylko map.

2022-06-01 11:04 UTC, purbanski-deftcode commented on assets/js/main.js
> +    }
Całe `toggleAriaExpanded` może być skrócone do:
```
element.setAttribute(ARIA_EXPANDED, element.getAttribute(ARIA_EXPANDED) ? 'false' : 'true');
```

2022-06-01 11:04 UTC, purbanski-deftcode commented on assets/js/main.js
> +    element.classList.toggle('noscroll');
Ogólnie jak już ciśniesz ze constami do klas to warto wszystkie stringi tam wynieść do góry. Klasę `active` czy też `noscroll` także. Możesz też wynieść do constów atrybuty dla `ARIA_EXPENDED` i ogólnie pozbyć się stringów z głównego kodu.

2022-06-01 11:04 UTC, purbanski-deftcode commented on assets/js/main.js
> +getElement(NAVBAR_MOBILE__BUTTON_ID).addEventListener('click', handleMobileNav);
Wszystkie główne addEventListenery możesz przenieść albo na sam dół albo na samą górę żeby jasno było widać gdzie inicjalizujesz i jak aplikację.

2022-06-06 19:30 UTC, merged